### ISSUE TITLE
Migration to tiles 3

### ISSUE THREAD

**Issue by rslima** [thymeleaf/thymeleaf-extras-tiles2#10]
Would it be hard to migrate the support for Tiles 3? It seems Spring 3.2 now supports Tiles 3 so I was wondering if Thymeleaf could support Tiles 3 as well.

**Comment by danielfernandez** [comment]
Providing support for Tiles 3 is in the TO-DO, probably as a different module (`thymeleaf-extras-tiles3`), because Tiles 2 and 3's architectures are quite different and not compatible.
