### ISSUE TITLE
mvn clean:clean install  gets stuck at maven-gpg-plugin:1.1:sign

### ISSUE THREAD

**Issue by ericfrancis** [thymeleaf/thymeleaf-extras-tiles2#11]
My command window stays at GPG Passphrase: *

**Comment by danielfernandez** [comment]
This is a maven bug: http://jira.codehaus.org/browse/MGPG-22

Anyway, note there is no need for you to build the .jar files from source. You can download them from http://search.maven.org/#artifactdetails%7Corg.thymeleaf.extras%7Cthymeleaf-extras-tiles2%7C2.0.0%7Cjar or simply use them in your Maven projects using the data explained at https://github.com/thymeleaf/thymeleaf-extras-tiles2#maven-info

**Comment by ericfrancis** [comment]
Ok, thanks. I couldn't find the jar when I looked.
