### ISSUE TITLE
How to use EL for jsp type attribte in tiles template definitions file?

### ISSUE THREAD

**Issue by gitacc** [thymeleaf/thymeleaf-extras-tiles2#13]
The following expression for content attribute doesnt work. 

<definition name="account" templateType="jsp" preparer="viewPreparer">
          <put-attribute name="content" type="jsp" expression="${requestScope.viewPathAccordingToDevice}/account/content.jsp"/>
  </definition>

**Comment by danielfernandez** [comment]
Sorry, GitHub doesn't show your code. Could you post it again?
