### ISSUE TITLE
ThymeleafTilesView to expose Thymeleaf's own evaluation context as a model variable in order to support ConversionService

### ISSUE THREAD

**Issue by philiptran** [thymeleaf/thymeleaf-extras-tiles2#19]
Hi Daniel,

First of all, thank you so much for this great project. I'm evaluating this project in order to make the right recommendation to our management on the technologies for use in the View layer.

Please bare with me if there is missing information as this is my first post.

Evaluation Stack:
- Thymeleaf 2.1.2.RELEASE
- Thymeleaf Extras Tiles2 Integration 2.1.0.RELEASE
- Spring Framework 3.2.6.RELEASE

The new syntax, double braces "{{", to invoke the ConversionService introduced in Thymeleaf 2.1.2 does not work. After tracing the bug, it turns out the ThymeleafTilesView needs to expose thymeleafEvaluationContext as a model variable that is similar to the one in ThymeleafView. I have tried to fix the bug by adding the following code after line 165 of  ThymeleafTilesView and it works.

```
final ApplicationContext applicationContext = getApplicationContext();
// Expose Thymeleaf's own evaluation context as a model variable
final ConversionService conversionService = (ConversionService) request
                .getAttribute(ConversionService.class.getName()); // might be null!
final ThymeleafEvaluationContext evaluationContext = new ThymeleafEvaluationContext(
                applicationContext, conversionService);
mergedModel.put(ThymeleafEvaluationContext.THYMELEAF_EVALUATION_CONTEXT_CONTEXT_VARIABLE_NAME,
                        evaluationContext);
```

Let me know how could I help to add this fix to the next release of this project. Thank you.

**Comment by danielfernandez** [comment]
Confirmed. The `ThymeleafTilesView` class is lacking the initialization of a `ThymeleafEvaluationContext` instance as is done at the non-Tiles `ThymeleafView` class here: https://github.com/thymeleaf/thymeleaf-spring3/blob/thymeleaf-spring3-2.1.2.RELEASE/src/main/java/org/thymeleaf/spring3/view/ThymeleafView.java?source=c#L245-249

**Comment by danielfernandez** [comment]
Updated 2.1.1-SNAPSHOT.

Note that this library has been divided into several different artifacts:
- `thymeleaf-extras-tiles2` including the core of the Tiles dialect.
- `thymeleaf-extras-tiles2-spring3` including the Spring integration artifacts, for Spring 3.x.
- (soon-to-be) `thymeleaf-extras-tiles2-spring4` for Spring 4 integration.

For users of Thymeleaf + Tiles 2 + Spring 3.x, including the `thymeleaf-extras-tiles2-spring3` dependency should suffice.
